blog/urls.py
from django.conf.urls import include, url

from . import views
urlpatterns = [
	url(r'<int:slug>/', views.blog_page, name='blog_page')
]

team/models.py
from django.contrib.auth.models import User
from django.forms import widgets
from django import forms
from django.db import models
from wagtail.snippets.models import register_snippet
from wagtail.search import index
from wagtail.core.models import Page
from wagtail.admin.edit_handlers import FieldPanel, MultiFieldPanel, StreamFieldPanel
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.snippets.edit_handlers import SnippetChooserPanel
from wagtail.core import blocks
from modelcluster.fields import ParentalKey
from wagtail.admin.edit_handlers import (
    FieldPanel, FieldRowPanel,
    InlinePanel, MultiFieldPanel
)
from wagtail.core.fields import RichTextField, StreamField
from wagtail.contrib.forms.models import AbstractForm, AbstractFormField
from wagtailcaptcha.models import WagtailCaptchaForm


class FormField(AbstractFormField):
    page = ParentalKey('JoinForm', on_delete=models.CASCADE, related_name='form_fields')



class JoinForm(WagtailCaptchaForm):
    paragraph = RichTextField(blank=True)
    describe_list = StreamField([
        ('list', blocks.ListBlock(blocks.CharBlock(label="Пункт списка"), icon="list-ul", template = 'blocks/list_block.html')),
    ])

    content_panels = AbstractForm.content_panels + [
        FieldPanel('paragraph', classname="full"),
        StreamFieldPanel('describe_list', classname="full"),
        InlinePanel('form_fields', label="Form fields"),
    ]

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)

        for name, field in form.fields.items():
            field.label = ''
            # here we want to adjust the widgets on each field
            # if the field is a TextArea - adjust the rows
            #from https://stackoverflow.com/questions/48321770/how-to-modify-attributes-of-the-wagtail-form-input-fields
            if isinstance(field.widget, widgets.Input):
                field.widget.attrs.update({'placeholder': field.help_text})
            if isinstance(field.widget, widgets.Textarea):
                field.widget.attrs.update({'placeholder': field.help_text, 'rows': 4})
            field.help_text= ''
        return form


@register_snippet
class TeamMemberRole(models.Model):
    name = models.CharField(max_length=40, blank=False, null=True)
    plural = models.CharField(max_length=40, blank=False, null=True, help_text='Название во множественном числе')
    panels = [
        FieldPanel('name'),
        FieldPanel('plural'),
    ]

    class Meta:
        verbose_name_plural = 'Роль в команде проекта'


    def __str__(self):
        return self.name


@register_snippet
class TeamMember(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='custom_userprofile', null=False, blank=False)
    info = models.CharField(max_length=100, blank=True)
    role = models.ForeignKey(TeamMemberRole, models.SET_NULL, null=True, blank=True)
    specificrole = models.CharField(max_length=100, blank=True)
    facebook = models.URLField(
        help_text='Your Facebook page URL',blank=True)
    instagram = models.CharField(
        max_length=255, help_text='Your Instagram username, without the @', blank=True)
    twitter = models.URLField(
        help_text='URL на аккаунт в Twitter', blank=True)
    vk = models.URLField(
        help_text='URL vk.com', blank=True)
    photo = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    panels = [
        FieldPanel('user'),
        FieldPanel('info'),
        FieldPanel('role'),
        FieldPanel('specificrole'),
        ImageChooserPanel('photo'),
        MultiFieldPanel([
            FieldPanel('facebook'),
            FieldPanel('instagram'),
            FieldPanel('twitter'),
            FieldPanel('vk'),
        ],heading='Аккаунты в социальных сетях'),
        
    ]

    def __str__(self):
        return self.user.get_full_name()

    class Meta:
        verbose_name_plural = 'Команда проекта'

    search_fields = [
        index.SearchField('user'),
        index.SearchField('info'),
    ]




class TeamIndex(Page):
    content_panels = Page.content_panels


    def get_context(self,request):
        # Update context to include only published posts, ordered by reverse-chron
        context = super().get_context(request)
        roles = TeamMemberRole.objects.all().order_by('id')
        context['roles'] = roles
        return context

team/views.py
from django.shortcuts import render

# Create your views here.

team/templates/team/join_form.html
{% extends 'base.html' %}
{% load static wagtailuserbar %}
{% load wagtailimages_tags %}
{% load wagtailcore_tags %}
{% block content %}
{%block join_form%}
 <div id="content">
<div class="holder-bg type-2 parallax-section" data-bg="{% static 'images/2059x1000_bg.jpg' %}">

	        <div class="container">
	        	<div class="row">
	        		<div class="col-sm-6">
	        			
	        			<h3 class="section-title">{{ page.title }}</h3>
	        			<div class="text-wrap">
	        				<p class="text-size-medium">{{page.paragraph|richtext}} </p>
	        			</div>
						
						<div class="fw-medium">
							<div class="small-title">У нас:</div>
		        			{% for block in page.describe_list %}
                                {% include_block block %}
                            {% endfor %}
                        </div>

	        		</div>
	        		<div class="col-sm-6">
						<form action="{{page.url}}" method="POST">
				            {% csrf_token %}
				             {% for field in page.get_form %}

							        {{ field.errors }}
							        {{ field.label_tag }} {{ field }}

							{% endfor %}
			                <button type="submit" class="btn">Отправить</button>
				        </form>
	        			<form>
                

			                

			            </form>


	        		</div>
	        	</div>
	        </div>
	        
	    </div>
</div>

{%endblock%}
{% endblock %}

team/templates/team/join_form_landing.html
Запрос обрабатывается, вы будете перенаправлены через несколько секунд
<script type="text/javascript">
	setTimeout(function(){
  window.history.back()
}, 2000);
</script>

team/templates/team/team_index.html
{% extends 'base.html' %}
{% load static wagtailuserbar %}
{% load wagtailimages_tags %}
{% load wagtailcore_tags %}
{% block content %}
    <!-- - - - - - - - - - - - - - Content - - - - - - - - - - - - - - - - -->

    <div id="content">

<!-- - - - - - - - - - - - - - Breadcrumbs - - - - - - - - - - - - - - - - -->

	    <div class="breadcrumbs-wrap">

	      <div class="container">
	        
	        <h1 class="page-title">{{page.title}}</h1>

	        {% if self.get_ancestors|length > 1 %}
				<ul class="breadcrumbs">

				{% for page in self.get_ancestors %}
				{% if page.is_root == False %}
				<li><a href="{{page.url}}">{{ page.title }}</a></li>
				{% endif %}
				{% endfor %}

				<li>{{ page.title }}</li>

				</ul>
			{% endif %}

	      </div>

	    </div>
	    <!-- posts - posts which get if set tag-->
		
	    <!-- - - - - - - - - - - - - end Breadcrumbs - - - - - - - - - - - - - - - -->

    	<div class="page-section type2">
    		
    		<div class="container">
    			{%for role in roles %}
    				
    			<div class="content-element">
    				
    				
    				

    				<h3>{{role.plural}}</h3>
					
					<!-- team section -->
	    			<div class="team-holder fx-col-3">
		              
		              	<!-- team element -->
		              	{% for member in role.teammember_set.all %}
		              	<div class="team-item">

			                <div class="team-member">

			                    {% if member.photo %}
			                    {% image member.photo fill-360x360 as img %} 
							    	<a href="#" class="member-photo"><img src="{{img.url}}" alt="{{img.alt}}"></a>
								{% endif %}
			                  	<div class="member-info">
			                    	<h5 class="member-name"><a href="#">{{member.user.get_full_name}}</a></h5>
			                    	<h6 class="member-position">{%if member.specificrole %}{{member.specificrole}}{%else%}{{role.name}}{%endif%}</h6>
			                    	<p>{{member.info}}</p>
			                  	</div>
			                  	<ul class="social-icons">
									{%if member.facebook%}
					                <li class="fb-icon"><a href="{{member.facebook}}" target="_blank"><i class="icon-facebook"></i></a></li>
					                {%endif%}
					                {%if member.vk%}
					                <li class="tweet-icon"><a href="{{member.vk}}" target="_blank"><i class="icon-vkontakte"></i></a></li>
					                {%endif%}
					                {%if member.twitter%}
					                <li class="tweet-icon"><a href="{{member.twitter}}" target="_blank"><i class="icon-twitter"></i></a></li>
					                {%endif%}
					                {%if member.instagram%}
					                <li class="insta-icon"><a href="{{member.instagram}}" target="_blank"><i class="icon-instagram-4"></i></a></li>
					                {%endif%}

				              	</ul>
			                </div>

		              	</div>
		              	{% endfor %}
		              
		            </div>

    			</div>
    			
    			{%endfor%}

    		</div>

    	</div>

    	{%block joinform%}{%include 'team/includes/join_form.html' %}{%endblock%}

    <!-- - - - - - - - - - - - - end Content - - - - - - - - - - - - - - - -->
 </div>
{% endblock %}